openebs:
  mayastor:
    csi:
      node:
        initContainers:
          enabled: false
    etcd:
      resources:
        requests:
          cpu: 1m
          memory: 256Mi
        limits:
          cpu: 375m
          memory: 384Mi
      volumePermissions:
        resourcesPreset: "none"
        resources:
          requests:
            cpu: 1m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 192Mi
  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: false