# Global Values
repoUrl: 'https://github.com/antodoms/homelab.git'
targetRevision: main
destinationServer: ''
argoNamespace: argocd
argoProject: ''

# ArgoCD Values
argoCd:
  enable: true
  createNamespace: true

certManager:
  enable: true
  createNamespace: true

trustManager:
  enable: true
  createNamespace: true

cilium:
  enable: true
  createNamespace: true

adguard:
  enable: true
  createNamespace: true

# MetalLB
metallb:
  enable: true
  addressPool: ""

# Kube Prometheus Stack
kubePrometheusStack:
  enable: true
  createNamespace: true

# VPA Values
vpa:
  enable: true
  createNamespace: true

localPathStorage:
  enable: false
  createNamespace: true

mayastor:
  enable: true
  createNamespace: true

# uses kube-system namespace
talosCcm:
  enable: false

mediaServerOperator:
  enable: true
  createNamespace: true
  general:
    storage:
      customVolume: true

kubeshark:
  enable: false
  createNamespace: true