{{- if and (.Values.cilium) (.Values.cilium.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/cilium
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        cilium:
        {{- toYaml .Values.cilium | nindent 10 }}
      parameters:
        - name: clusterLoadBalancerIpRange
          value: {{ .Values.clusterLoadBalancerIpRange }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: kube-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace={{ .Values.cilium.createNamespace }}
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}