{{- if and (.Values.cloudnativePg) (.Values.cloudnativePg.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/cloudnative-pg
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        cloudnative-pg:
        {{- toYaml .Values.cloudnativePg | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: cnpg-system
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - argocd-controller
        - argocd-application-controller
      jsonPointers:
        - /metadata/annotations
        - /metadata/managedFields
        - /metadata/labels
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace={{ .Values.cloudnativePg.createNamespace }}
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
