{{- if and (.Values.dockerRegistry) (.Values.dockerRegistry.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/docker-registry
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        docker-registry:
        {{- toYaml .Values.dockerRegistry | nindent 10 }}
      parameters:
      - name: docker-registry.ingress.hosts[0]
        value: registry.{{ .Values.ingressDomain }}
      - name: docker-registry.ingress.tls[0].hosts[0]
        value: registry.{{ .Values.ingressDomain }}
      - name: docker-registry.ingress.tls[0].secretName
        value: registry-general-tls
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: docker-registry
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace={{ .Values.dockerRegistry.createNamespace }}
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}