{{- if and (.Values.envoyGateway) (.Values.envoyGateway.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/envoy-gateway
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        ingressDomain: {{ .Values.ingressDomain }}
        gateway-helm:
        {{- toYaml .Values.envoyGateway | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace={{ .Values.envoyGateway.createNamespace }}
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end -}}
