{{- if and (.Values.localPathStorage) (.Values.localPathStorage.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/local-path-storage
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: local-path-storage
  syncPolicy:
    syncOptions:
    - CreateNamespace={{ .Values.kubePrometheusStack.createNamespace }}
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}