{{- if and (.Values.metallb) (.Values.metallb.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/metallb
    targetRevision: {{ .Values.targetRevision }}
    kustomize:
      patches:
        - target:
            kind: IPAddressPool
            name: default
          patch: |-
            - op: replace
              path: /spec/addresses/0
              value: {{ .Values.metallb.addressPool }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle

{{- end -}}