{{- if and (.Values.openobserveCollector) (.Values.openobserveCollector.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve-collector
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/openobserve-collector
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - secrets://secrets.yaml
      values: |
        openobserve-collector:
        {{- toYaml .Values.openobserveCollector | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: openobserve-collector
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace={{ .Values.openobserveCollector.createNamespace }}
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
