{{- if ((.Values.openebs).enable) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ required "repoUrl value is required" .Values.repoUrl }}
    path: addons/openebs
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        openebs:
          {{- toYaml .Values.openebs | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: openebs
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace={{ .Values.openebs.createNamespace }}
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
    - group: batch
      kind: Job
      name: openebs-etcd-pre-upgrade
      jsonPointers:
        - /spec/template
    - group: ""
      kind: Secret
      name: openebs-etcd-jwt-token
      jsonPointers:
        - /data/jwt-token.pem
    - group: apps
      kind: StatefulSet
      name: openebs-etcd
      jqPathExpressions:
        - .spec.template.metadata.annotations["checksum/token-secret"]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-deps
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ required "repoUrl value is required" .Values.repoUrl }}
    path: addons/openebs-deps
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        openebsDeps:
          {{- toYaml .Values.openebs | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: openebs
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
{{- end -}}