services:
  base: &base
    image: controlcenter
    build:
      context: .
      target: dev
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    environment:
      - RACK_ENV=development
      - RAILS_ENV=development
      - SOLID_QUEUE_IN_PUMA=true
      - BUNDLE_DEPLOYMENT=0
      - BUNDLE_WITHOUT=production
    env_file:
      - .env

  web:
    <<: *base
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - deps_css
    ports:
      - "3000:3000"

  deps_css:
    <<: *base
    command: ["./bin/rails", "tailwindcss:watch"]

volumes:
  bundle: