{{ if .Values.cilium.l2announcements.enabled }}
{{ $ip_range := split "-" .Values.clusterLoadBalancerIpRange }}
{{ if eq (len $ip_range) 2 }}
apiVersion: "cilium.io/v2alpha1"
kind: "CiliumLoadBalancerIPPool"
metadata:
  name: "external"
spec:
  blocks:
    - start: {{ $ip_range._0 }}
      stop: {{ $ip_range._1 }}
---
{{ end }}
{{ end }}