---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
spec:
  isCA: true
  commonName: "homelab ingress"
  subject:
    organizations:
      - "{{ .Values.certManagerDeps.ingressDomain }}"
    organizationalUnits:
      - kubernetes
  privateKey:
    algorithm: "ECDSA" # NB Ed25519 is not yet supported by chrome 93 or firefox 91.
    size: 256
  duration: "4320h" # NB 4320h (180 days). default is 2160h (90 days).
  secretName: "ingress-tls"
  issuerRef:
    name: selfsigned
    kind: "ClusterIssuer"
    group: "cert-manager.io"