ingressDomain: "homelab.lam" # override this value as argo app
cert-manager:
  extraArgs:
  - --enable-certificate-owner-ref=true
  crds:
    enable: true
    keep: true
  enable: true
  createNamespace: true
  serviceAccountName: cert-manager
  ingressShim:
    defaultIssuerName: letsencrypt
    defaultIssuerKind: ClusterIssuer
  webhook:
    serviceAccount:
      create: true
      name: cert-manager-webhooks
  cainjector:
    serviceAccount:
      create: true
      name: cert-manager-cainjector
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    deploymentAnnotations:
      argocd.argoproj.io/sync-wave: "1"
    podAnnotations:
      argocd.argoproj.io/sync-wave: "1"
    serviceAnnotations:
      argocd.argoproj.io/sync-wave: "1"
  serviceAccount:
    create: true
    name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "1"
  deploymentAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  podAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  serviceAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  prometheus:
    servicemonitor:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
  podmonitor:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
  startupapicheck:
    podAnnotations:
      argocd.argoproj.io/sync-wave: "1"
