mayastor:
  mayastor:
    csi:
      node:
        initContainers:
          enabled: false
  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: false
  etcd:
    persistence:
      storageClass: "mayastor-etcd-localpv"
  loki-stack:
    loki:
      persistence:
        storageClassName: "mayastor-loki-localpv"
  localpv-provisioner:
    hostpathClass:
      enabled: true