mayastor:
  etcd:
    persistence:
      storageClass: "mayastor-etcd-localpv"
  loki-stack:
    loki:
      persistence:
        storageClassName: "mayastor-loki-localpv"
  localpv-provisioner:
    hostpathClass:
      enabled: true