name: config
on:
  push:
    paths:
        - .github/workflows/config.yaml
        - config/**
  workflow_dispatch:

permissions:
    id-token: write
    contents: read
    actions: write

jobs:
  upload:
    strategy:
        matrix:
          region: [ap-southeast-2]
          account: [homelab]
          include:
              - account: homelab
                account_id: 780008751869
        fail-fast: false
    
    name: ${{ matrix.account }}-${{ matrix.region }}
    concurrency:
      group: ${{ matrix.account }}-${{ matrix.region }}-config
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.region }}
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/github-action

      - name: upload main json to s3
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          aws s3 cp ./config/vars/${{ matrix.account }}.json s3://zetech.terraform-state.${{ matrix.account }}/config/${{ matrix.account }}.json

      - name: upload branch json to s3
        if: github.ref != 'refs/heads/main'
        shell: bash
        run: |
          aws s3 cp ./config/vars/${{ matrix.account }}.json s3://zetech.terraform-state.${{ matrix.account }}/config/${{ github.ref }}/${{ matrix.account }}.json